version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: postcode_validator:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: postcode_validator
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]